# Generated by Django 5.0.9 on 2024-11-28 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpotFinder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pessoa",
            options={},
        ),
        migrations.AlterModelManagers(
            name="pessoa",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="data_nascimento",
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="password",
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="username",
        ),
        migrations.AddField(
            model_name="pessoa",
            name="cpf",
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pessoa",
            name="datadenascimento",
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pessoa",
            name="usuario",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="carro",
            name="proprietario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carros",
                to="SpotFinder.pessoa",
            ),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="email",
            field=models.EmailField(default=9, max_length=254),
            preserve_default=False,
        ),
    ]
